version: '2'
services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: local-dynamodb
    restart: always
    volumes:
      - ./db:/home/dynamodblocal/data
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"
networks:
  local-dynamodb:
    name: local-dynamodb
