// Code generated by tygo. DO NOT EDIT.

//////////
// source: enum.go

export type Id = number /* int */;
export const WordGuess: Id = 0;
export type TeamName = string;
export const None: TeamName = "";
export const RedTeam: TeamName = "red";
export const BlueTeam: TeamName = "blue";
export type State = string;
export const PreMatch: State = "prematch";
export const InProgress: State = "inprogress";
export const PostMatch: State = "postmatch";

//////////
// source: request.go

export interface SendChatRequest {
  text: string;
}
export interface LoadChatRequest {
  timestamp: number /* int64 */;
}
export interface SessionUseRequest {
  sessionId: string;
}
export interface CreateAndJoinRequest {
  name: string;
}

//////////
// source: response.go

export interface Wrapper {
  service: string;
  action: string;
  data: string;
}
export interface ErrorResponse {
  error: string;
}
export interface SessionResponse {
  sessionId: string;
}
export interface SendChatResponse {
  text: string;
  timestamp: number /* int64 */;
  playerId: string;
}
export interface LoadChatResponse {
  messages: SendChatResponse[];
}
export interface JoinResponse {
  lobbyId: string;
}
export interface GetResponse {
  lobby: Details;
  player: Player;
}
export interface PlayerJoinResponse {
  player: Player;
}
export interface PlayerLeftResponse {
  player: Player;
}

//////////
// source: settings.go

export type Encoded = string;
export interface WordGuessSettings {
  blackCards: number /* int */;
  whiteCards: number /* int */;
  colouredCards: number /* int */;
  dynamic: boolean;
}

//////////
// source: types.go

export interface Connection {
  ConnectionId: string;
  SessionId: string;
}
export interface Player {
  id: string;
  name: string;
  points: number /* int32 */;
  isAdmin: boolean;
  isOnline: boolean;
}
export interface Chat {
  lobbyId: string;
  playerId: string;
  timestamp: number /* int64 */;
  message: string;
}
export interface Details {
  players: Player[];
  lobbyId: string;
  settings: Settings;
  inGame: boolean;
  gameSessionId: string;
}
export interface Lobby {
  lobbyId: string;
  settings: Settings;
  inGame: boolean;
  gameSessionId: string;
}
export interface Settings {
  gameId: Id;
  maxPlayers: number /* int */;
  teams: number /* int */;
  game: WordGuessSettings;
}
