name: Build

on:
  pull_request:
    branches:
      - main

env:
  GOOS: linux
  GOARCH: amd64

jobs:
  build:
    strategy:
      matrix:
        function: [ disconnect, connect, default ]
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - run: go version

      - name: Build
        run: |
          go mod tidy
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o "./dist/${{ matrix.function }}/main" "./pkg/${{ matrix.function }}-main.go"

      s
      - name: Zip
        working-directory: ./dist/${{ matrix.function }}
        run: |
          zip main.zip main

      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.function }}
          path: dist/${{ matrix.function }}/main.zip