name: Build

on:
 pull_request:
  branches:
   - main

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: Clone repository
     uses: actions/checkout@v2

   - uses: actions/setup-go@v4
     with:
        go-version: 1.15

   - name: Build
     run: ./scripts/compile-go.sh 

   - name: Upload Disconnect Build
     uses: actions/upload-artifact@v1
     with:
      name: build-disconnect
      path: dist/disconnect

   - name: Upload Connect Build
     uses: actions/upload-artifact@v1
     with:
      name: build-connect
      path: dist/connect

   - name: Upload Default Build
     uses: actions/upload-artifact@v1
     with:
      name: build-default
      path: dist/default