name: Deploy

on:
  pull_request:
    types:
      - closed

concurrency: deploy

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: aws
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download Disconnect Assets
        uses: dawidd6/action-download-artifact@v2
        with:
          name: build-disconnect
          workflow: build.yml
          workflow_conclusion: success
          commit: ${{ github.event.pull_request.head.sha }}
          path: ./build-disconnect

      - name: Zip Discconect
        working-directory: ./build-disconnect
        run: |
          mv disconnect main
          zip disconnect.zip main
          
      - name: Upload Disconnect
        working-directory: ./build-disconnect
        uses: actions/upload-artifact@v1
        with:
          name: disconnect
          path: disconnect.zip

      - name: Upload Disconnect
        uses: actions/upload-artifact@v1
        working-directory: ./build-disconnect
        with:
          name: disconnect
          path: disconnect.zip

      - name: Update Discconect
        working-directory: ./build-disconnect
        run: |
          aws lambda update-function-code --function-name Disconnect --zip-file fileb://disconnect.zip

      # - name: Download Connecy Assets
      #   uses: dawidd6/action-download-artifact@v2
      #   with:
      #     name: build-connect
      #     workflow: build.yml
      #     workflow_conclusion: success
      #     commit: ${{ github.event.pull_request.head.sha }}
      #     path: ./build-connect

      # - name: Download Default Assets
      #   uses: dawidd6/action-download-artifact@v2
      #   with:
      #     name: build-default
      #     workflow: build.yml
      #     workflow_conclusion: success
      #     commit: ${{ github.event.pull_request.head.sha }}
      #     path: ./build-default
