name: Deploy

on:
  pull_request:
    types:
      - closed

concurrency: deploy

jobs:
  apply:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: aws
    steps:
      - uses: actions/checkout@v3

      - name: Download Disconnect Assets
        uses: dawidd6/action-download-artifact@v2
        with:
          name: build-disconnect
          workflow: build.yml
          workflow_conclusion: success
          commit: ${{ github.event.pull_request.head.sha }}
          path: ./build-disconnect

      - name: Download Connecy Assets
        uses: dawidd6/action-download-artifact@v2
        with:
          name: build-connect
          workflow: build.yml
          workflow_conclusion: success
          commit: ${{ github.event.pull_request.head.sha }}
          path: ./build-connect

      - name: Download Default Assets
        uses: dawidd6/action-download-artifact@v2
        with:
          name: build-default
          workflow: build.yml
          workflow_conclusion: success
          commit: ${{ github.event.pull_request.head.sha }}
          path: ./build-default
